# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(srctree)/include
EXTRA_CFLAGS += -I$(srctree)/drivers/power/mm8013c_fg_mmi

mm8013c_fg_mmi-objs += mm8013c_battery.o
obj-m += mm8013c_fg_mmi.o
