HAVE_KERNEL_4_19 = 0

HAVE_KERNEL_5_4 = $(shell test -d $(srctree) && echo 1)

ifeq ($(HAVE_KERNEL_4_19),1)
        KERNEL_SOURCE_PATH ?= kernel/msm-4.19
else ifeq ($(HAVE_KERNEL_5_4),1)
        KERNEL_SOURCE_PATH ?= kernel/msm-5.4
else
        KERNEL_SOURCE_PATH ?= kernel/msm-4.9
endif

HAVE_TECHPACK_CAMERA = 0

ifeq ($(HAVE_TECHPACK_CAMERA),1)
        KERNEL_CAMERA_DRIVER_PATH ?= $(srctree)/techpack/camera/drivers
        EXTRA_CFLAGS += -DCONFIG_SPECTRA_CAMERA=1
        EXTRA_CFLAGS += -I$(KERNEL_CAMERA_DRIVER_PATH)/../include
        EXTRA_CFLAGS += -I$(KERNEL_CAMERA_DRIVER_PATH)/../include/uapi
        EXTRA_CFLAGS += -I$(KERNEL_CAMERA_DRIVER_PATH)/../include/uapi/camera
else
        KERNEL_CAMERA_DRIVER_PATH ?= $(srctree)/drivers/media/platform/msm/camera
endif

EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(srctree)/include
EXTRA_CFLAGS += -I$(KERNEL_CAMERA_DRIVER_PATH)/cam_utils
EXTRA_CFLAGS += -I$(KERNEL_CAMERA_DRIVER_PATH)/cam_cpas/include
EXTRA_CFLAGS += -I$(KERNEL_CAMERA_DRIVER_PATH)/cam_sensor_module/cam_sensor_io
EXTRA_CFLAGS += -I$(KERNEL_CAMERA_DRIVER_PATH)/cam_sensor_module/cam_sensor_utils
EXTRA_CFLAGS += -I$(KERNEL_CAMERA_DRIVER_PATH)/cam_sensor_module/cam_cci
EXTRA_CFLAGS += -I$(KERNEL_CAMERA_DRIVER_PATH)/cam_req_mgr
EXTRA_CFLAGS += -I$(KERNEL_CAMERA_DRIVER_PATH)/cam_smmu

obj-m	+= cci_intf.o
