# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(srctree)/include
EXTRA_CFLAGS += -I$(srctree)/drivers/power/sm5602_fg_mmi

sm5602_fg_mmi-objs += sm5602_fg.o
obj-m += sm5602_fg_mmi.o
