# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(srctree)/include

moto_f_mass_storage-objs += f_mass_storage.o storage_common.o
obj-m += moto_f_mass_storage.o
