KERNEL_DIR_PATH = $(srctree)

KERNEL_VERSION_NAME = $(shell basename $(KERNEL_DIR_PATH))

KERNEL_PLATFORM_PATH = $(srctree)

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(srctree)/include

KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../sensors/$(GKI_OBJ_MODULE_DIR)/Module.symvers

bu520xx-y := bu520xx_pen.o

obj-m += bu520xx_pen.o
