# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(srctree)/include \
		-I$(srctree)/drivers/input/touchscreen/nova_mmi

ifeq ($(filter m y, $(CONFIG_TOUCHSCREEN_NOVATEK_CHIPSET)),)
	obj-m := nova_mmi.o
endif

nova_mmi-objs += nt36xxx.o
nova_mmi-objs += nt36xxx_ext_proc.o
nova_mmi-objs += nt36xxx_fw_update.o
nova_mmi-objs += nt36xxx_mp_ctrlram.o
