# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(srctree)/include

ifneq ($(filter m y,$(CONFIG_MMI_BOOTCONFIG_SUPPORT)),)
        EXTRA_CFLAGS += -DCONFIG_MMI_BOOTCONFIG_SUPPORT
endif

obj-m += mmi-smbcharger-iio.o
