KERNEL_DIR_PATH = $(srctree)

KERNEL_VERSION_NAME = $(shell basename $(KERNEL_DIR_PATH))

KERNEL_PLATFORM_PATH = $(srctree)

# add -Wall to try to catch everything we can.
EXTRA_CFLAGS += -Wall
EXTRA_CFLAGS += -I$(srctree)/include

ifneq ($(filter m y,$(CONFIG_HALL_PASSIVE_PEN)),)
	EXTRA_CFLAGS += -DCONFIG_HALL_PASSIVE_PEN
endif


KBUILD_EXTRA_SYMBOLS += $(CURDIR)/$(KBUILD_EXTMOD)/../../sensors/$(GKI_OBJ_MODULE_DIR)/Module.symvers

obj-m += hall_pen.o
obj-m += hall_folio.o
